---
extends: default

rules:
  document-start: disable
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false", "on"]
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: true

ignore:
  - node_modules/
  - .git/
