import {
  Activity,
  AppWindow,
  ArrowUp,
  BadgeCheck,
  Bell,
  BellRing,
  Bot,
  Clock,
  CloudOff,
  Columns,
  Copy,
  DollarSign,
  ExternalLink,
  Eye,
  EyeOff,
  FileDiff,
  FolderGit2,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Globe,
  Hash,
  History,
  Keyboard,
  LayoutGrid,
  Layers,
  ListChecks,
  ListOrdered,
  ListTodo,
  Loader,
  MessageSquare,
  MessagesSquare,
  MousePointerClick,
  PanelBottom,
  PanelRight,
  Pencil,
  Play,
  RefreshCw,
  Search,
  ShieldCheck,
  Tag,
  Tags,
  Ticket,
  Wrench,
  type LucideIcon,
} from 'lucide-react'
import type { DesktopIcon } from '@/lib/desktopPage'

/**
 * Icon NAME → lucide component, for the strings in `lib/desktopPage.ts` — the split
 * `SkillsSection` and `FeaturesContent` make, and for the same reason: the data module is
 * read by the root vitest suite, which has no `lucide-react` to resolve.
 *
 * Exhaustive by type: a name added over there and not here is a `tsc` error at this map.
 */
export const DESKTOP_ICONS: Record<DesktopIcon, LucideIcon> = {
  ListTodo,
  MousePointerClick,
  FolderGit2,
  GitBranch,
  Layers,
  BellRing,
  Wrench,
  ShieldCheck,
  Gauge,
  Keyboard,
  Columns,
  Search,
  Bell,
  AppWindow,
  DollarSign,
  Clock,
  Pencil,
  RefreshCw,
  Ticket,
  ExternalLink,
  Tag,
  Play,
  ListOrdered,
  GitCommitHorizontal,
  CloudOff,
  GitPullRequest,
  PanelBottom,
  MessageSquare,
  Eye,
  Activity,
  Globe,
  FileDiff,
  LayoutGrid,
  History,
  Copy,
  ArrowUp,
  Hash,
  EyeOff,
  Loader,
  ListChecks,
  GitMerge,
  MessagesSquare,
  PanelRight,
  Bot,
  Tags,
  BadgeCheck,
}
